baseURL = "https://hencter.github.io/"
languageCode = "zh-CN"
# 为保证文章字数统计正确
hasCJKLanguage = "true"
title = "亦幸's Blog"

publishDir = "docs"

copyright = "Copyright ©"

paginate = "3"

[author]
  name = "亦幸"

[menu]

[[menu.main]]
    identifier = "index"
    name = "INDEX"
    title = "blog section"
    url = "/"
    weight = 1

[[menu.main]]
    identifier = "post"
    name = "POST"
    title = "post"
    url = "/posts/"
    weight = 2

[[menu.main]]
    identifier = "webdev"
    name = "网盘"
    title = "Netdisc"
    url = "http://hencter.ys168.com/"
    weight = 3

[[menu.main]]
    identifier = "about"
    name = "ABOUT"
    title = "about"
    url = "/about/"
    weight = 4
